<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PreserveCompilationContext>true</PreserveCompilationContext>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="Itmo.Dev.Platform.Testing" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="FluentAssertions"/>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\service\Application\BankApp.Application.Abstractions\BankApp.Application.Abstractions.csproj" />
      <ProjectReference Include="..\..\src\service\Main\Main.csproj" />
    </ItemGroup>

</Project>